version: 2

sources:
  - name: pdga
    tables:
      - name: event_requests
        meta:
          dagster:
            asset_key: ["event_requests"]
      - name: event_details
        meta:
          dagster:
            asset_key: ["event_details"]