pdga_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: edwetl
      password: edwetl
      port: 5432
      dbname: 'pdga'
      schema: 'pdga'
      threads: 1
      query_tag: dbt
