[sources.sql_database.credentials]
drivername = "snowflake"
database = "PDGA_DB"
password = "nottoday"
username = "TOMSMITH"
host = "NOPE-ABC123"
warehouse= "PDGA_WH"
role = "ACCOUNTADMIN"
schema = "PDGA"


[destination.postgres]
dataset_name = "pdga"
[destination.postgres.credentials]
database = "pdga"
username = "admin"
password = "betterlucknexttime"
host = "localhost"
port = 5432
connect_timeout = 15